apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: authentication
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"        
        autoscaling.knative.dev/maxScale: "10"      
        autoscaling.knative.dev/target: "100"        
    spec:
      containers:
        - image: mascorpion/ds:latest
          imagePullPolicy: Always
          command: ["authentication/authentication"]
          ports:
            - containerPort: 80   
              name: h2c                 
          env:
            - name: ENV_VAR
              value: "value2"                    
          resources:
            requests:
              cpu: "100m"                       
              memory: "128Mi"             
            limits:
              cpu: "500m"                     
              memory: "256Mi"   

---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: authorization
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"        
        autoscaling.knative.dev/maxScale: "10"      
        autoscaling.knative.dev/target: "100"        
    spec:
      containers:
        - image: mascorpion/ds:latest
          imagePullPolicy: Always
          command: ["authorization/authorization"]
          ports:
            - containerPort: 80     
              name: h2c              
          env:
            - name: ENV_VAR
              value: "value2"                    
          resources:
            requests:
              cpu: "100m"                       
              memory: "128Mi"             
            limits:
              cpu: "500m"                     
              memory: "256Mi"   


---


apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: scheduler
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"        
        autoscaling.knative.dev/maxScale: "1"      
        autoscaling.knative.dev/target: "100"        
    spec:
      containers:
        - image: mascorpion/ds:latest
          imagePullPolicy: Always
          command: ["scheduler/scheduler"]
          ports:
            - containerPort: 80  
              name: h2c                  
          env:
            - name: ENV_VAR
              value: "value2"                    
          resources:
            requests:
              cpu: "100m"                       
              memory: "128Mi"             
            limits:
              cpu: "500m"                     
              memory: "256Mi"   

---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: write-to-etcd
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"        
        autoscaling.knative.dev/maxScale: "10"      
        autoscaling.knative.dev/target: "100"        
    spec:
      containers:
        - image: mascorpion/ds:latest
          imagePullPolicy: Always
          command: ["writeToEtcd/writeToEtcd"]
          ports:
            - containerPort: 80  
              name: h2c                  
          env:
            - name: ENV_VAR
              value: "value2"                    
          resources:
            requests:
              cpu: "100m"                       
              memory: "128Mi"             
            limits:
              cpu: "500m"                     
              memory: "256Mi"   

---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: metric-collector
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"        
        autoscaling.knative.dev/maxScale: "10"      
        autoscaling.knative.dev/target: "100"        
    spec:
      containers:
        - image: mascorpion/ds:latest
          imagePullPolicy: Always
          command: ["metricCollector/metricCollector"]
          ports:
            - containerPort: 80    
              name: h2c                
          env:
            - name: ENV_VAR
              value: "value2"                    
          resources:
            requests:
              cpu: "100m"                       
              memory: "128Mi"             
            limits:
              cpu: "500m"                     
              memory: "256Mi"  

---
