name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

    # Log in to Docker Hub using the token
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: mascorpion # Your Docker Hub username
        password: dckr_pat_mK4ngFETV5YtoZ45n6099-mfVMY

    # Build the Docker image
    - name: Build Docker Image
      run: |
        docker build -t mascorpion/ds:latest .

    # Push the Docker image to Docker Hub
    - name: Push Docker Image
      run: |
        docker push mascorpion/ds:latest
